export const SUPABASE_TABLES = {
  taskItems: "Task_item_rows",
  tasks: "Task_row",
  vendorCategories: "Vendor_Category",
  vendors: "Vendors_row",
  comboBoxes: "combo_boxes",
  expenses: "expenses_row",
  financeBills: "finance_bills_rows",
  financeCategories: "finance_categories_rows",
  influencerBargainHistory: "influencer_bargain_history_rows",
  influencerBrandPerformance: "influencer_brand_performance_rows",
  influencerCreate: "influencer_create_rows",
  influencerDispatch: "influencer_dispatch_rows",
  influencerPlatform: "influencer_platform_rows",
  influencerPricing: "influencer_pricing_rows",
  influencerProduct: "influencer_product_rows",
  influencerStatus: "influencer_status_rows",
  influencersInfo: "influencers_info_rows",
  logisticsWebhookLogs: "logistics_webhook_logs_rows",
  mainTasks: "main_tasks_rows",
  productBarcodes: "product_barcodes",
  productionBatches: "production_batches",
  purchaseOrderProducts: "purchase_order_products_rows",
  purchaseOrders: "purchase_orders_rows",
  qcBarcodes: "qc_barcodes",
  rawMaterialBarcodes: "raw_material_barcodes",
};
