-- Migration: Create influencer_post_dates_rows table for video post date scheduling
CREATE TABLE IF NOT EXISTS public.influencer_post_dates_rows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    influencer_id bigint NOT NULL,
    campaign_id text NOT NULL,
    video_number integer NOT NULL,
    post_date date,
    draft_date date,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.influencer_post_dates_rows ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated full access to influencer_post_dates_rows" ON public.influencer_post_dates_rows;
DO $$ BEGIN
  CREATE POLICY "Allow authenticated full access to influencer_post_dates_rows" ON public.influencer_post_dates_rows
    FOR ALL TO authenticated USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
