-- Migration: Create ticket_courier_partners table for custom persistent courier partners

CREATE TABLE IF NOT EXISTS ticket_courier_partners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_courier_partner_name_lower ON ticket_courier_partners (LOWER(TRIM(name)));

