-- Create ticket_issue_types table
CREATE TABLE IF NOT EXISTS ticket_issue_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create ticket_sub_issues table with foreign key to ticket_issue_types
CREATE TABLE IF NOT EXISTS ticket_sub_issues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_type_id BIGINT NOT NULL REFERENCES ticket_issue_types(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Case-insensitive unique indexes
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_issue_type_name_lower ON ticket_issue_types (LOWER(name));
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_sub_issue_name_lower ON ticket_sub_issues (issue_type_id, LOWER(name));

-- Foreign key lookup index
CREATE INDEX IF NOT EXISTS idx_sub_issues_issue_type_id ON ticket_sub_issues(issue_type_id);
